export const SHOW_APP = 'SHOW_APP';
export const HIDE_APP = 'HIDE_APP';

export const FETCH_POSTS_DATA = 'FETCH_POSTS_DATA';
export const READ_POSTS_DATA = 'READ_POSTS_DATA';

export const FETCH_POSTS_CACHE_ATTEMPT = 'FETCH_POSTS_CACHE_ATTEMPT';
export const FETCH_POSTS_CACHE_SUCCESS = 'FETCH_POSTS_CACHE_SUCCESS';
export const FETCH_POSTS_CACHE_FAIL = 'FETCH_POSTS_CACHE_FAIL';

export const READ_MOBILE_POSTS_CACHE_ATTEMPT = 'READ_MOBILE_POSTS_CACHE_ATTEMPT';
export const READ_MOBILE_POSTS_CACHE_SUCCESS = 'READ_MOBILE_POSTS_CACHE_SUCCESS';
export const READ_MOBILE_POSTS_CACHE_FAIL = 'READ_MOBILE_POSTS_CACHE_FAIL';

export const READ_WEB_API_CACHE_ATTEMPT = 'READ_WEB_API_CACHE_ATTEMPT';
export const READ_WEB_API_CACHE_SUCCESS = 'READ_WEB_API_CACHE_SUCCESS';
export const READ_WEB_API_CACHE_FAIL = 'READ_WEB_API_CACHE_FAIL';